apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gf6lro8ml-go 
  janus-idp.io/tekton: gf6lro8ml-go
  backstage.io/kubernetes-id: gf6lro8ml-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gf6lro8ml-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  