apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gf6lro8ml-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gf6lro8ml-go 
  name: gf6lro8ml-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gf6lro8ml-go 
